# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 02:28
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodinfo',
            name='gcontent',
            field=tinymce.models.HTMLField(verbose_name='\u6b63\u6587'),
        ),
    ]
