# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-21 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartinfo',
            name='ifsubmission',
        ),
    ]
