# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('df_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsubmission', models.BooleanField(verbose_name=False)),
                ('freight', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('paymentChoice', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=100)),
                ('sumPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ucart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_cart.CartInfo')),
            ],
        ),
    ]
